name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.0'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Start Memcached
        run: |
          sudo apt-get install -y memcached
          memcached -m 64 -u memcache -p 11211 -u memcache &
      - name: Start Redis
        run: |
          sudo apt-get install -y redis-server
          sudo service redis-server start
      - name: Run gem specs
        run: |
          bundle install
          bundle exec rspec
      - name: Run dummy app specs
        run: |
          cd spec/dummy
          bundle install
          bundle exec rspec