name: Publish Gem

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Build gem
        run: gem build rails_rate_limit.gemspec

      - name: Push gem to RubyGems
        run: gem push rails_rate_limit-*.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }} 